version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: my-db
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: P@ssw0rd

  # nodeapp:
  #   build: .
  #   container_name: nodeapp
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mysql
  #   environment:
  #     DB_HOST: mysql
  #     DB_USER: root
  #     DB_PASSWORD: P@ssw0rd
  #     DB_NAME: my-db